// web/src/views/PromptView.vue
<style>
.scroll-short {
    height: 200px;
    /* 设置组件容器的固定高度 */
    overflow: auto;
    /* 设置溢出部分自动滚动 */
}
</style>

<template>
    <div>
        <a-space align="center">
            <a-typography-title>{{ key }}</a-typography-title>

            <a-space direction="horizontal" align="baseline">
                <a-button @click="reload">
                    <template #icon>
                        <SyncOutlined />
                    </template>
                </a-button>
                <a-divider type="vertical"></a-divider>


            </a-space>
        </a-space>
        <a-row :gutter='6'>
            <a-col class="gutter-row" :span="12">

                <!-- <a-collapse>
                    <a-collapse-panel header="History">
                        <a-space direction="horizontal" align="baseline" v-for="h in prompt.history">
                            <a-button @click="copy(h)">
                                <template #icon>
                                    <CopyOutlined />
                                </template>
                            </a-button>
                            <p>{{ h }}</p>



                        </a-space>
                    </a-collapse-panel>
                </a-collapse> -->


                <a-card title="Prompt">
                    <template #extra>
                        <a-space>
                            <a-button
                                @click="() => { copy(JSON.stringify({ name: key, prompt: prompt.messages.filter((item: Message) => { return item.enable }) }, null, 2)) }">
                                CopyAll
                            </a-button>
                            <a-divider type="vertical"></a-divider>
                            <a-button @click="() => { prompt.messages.forEach((item) => item.enable = false) }">DisableAll
                            </a-button>
                            <a-button @click="() => { prompt.messages.forEach((item) => item.enable = true) }">EnableAll
                            </a-button>
                        </a-space>
                    </template>

                    <a-row justify="space-around">
                        <PromptInput :messages="prompt.messages" with-copy with-control
                            @order-up="index => order(index, -1)" @order-down="index => order(index, 1)"
                            @remove="index => deletePrompt(index)" @add="index => addPrompt(index, 'user', '')">
                        </PromptInput>
                    </a-row>

                    <a-divider>
                        <a-space>
                            <a-button @click="() => prompt.messages.push({ role: 'system', enable: true, content: '' })">
                                <template #icon>
                                    <PlusOutlined />
                                </template>
                            </a-button>
                        </a-space>

                    </a-divider>

                </a-card>

            </a-col>


            <a-col class="gutter-row" :span="12">
                <a-card title="Response">

                    <template #extra>
                        <a-space direction="horizontal">
                            <a-button @click="chat">Request</a-button>
                            <a-button @click="doCommit">Commit</a-button>
                            <a-button @click="() => copy(response)">Copy</a-button>
                            <a-button @click="responseToPrompt">Append</a-button>
                        </a-space>
                    </template>

                    <a-collapse>

                        <a-collapse-panel header="Prompt Preview">
                            <PromptCard :messages="prompt.messages.filter((i) => i.enable)"></PromptCard>
                        </a-collapse-panel>
                    </a-collapse>

                    <a-divider></a-divider>




                    <a-skeleton :loading="loading" active avatar>
                        <div>


                            <a-divider></a-divider>

                            <a-tabs v-model:activeKey="responseMode">
                                <a-tab-pane key="1" tab="Markown"> <vue-markdown :source="response"
                                        :options="{}"></vue-markdown></a-tab-pane>
                                <a-tab-pane key="2" tab="Text" force-render>
                                    <a-textarea v-model:value="response" :auto-size="{ maxRows: 16 }">
                                    </a-textarea>
                                </a-tab-pane>
                            </a-tabs>



                        </div>
                    </a-skeleton>

                </a-card>




                <a-card title="LLM Options">


                    <a-list item-layout="horizontal">
                        <a-list-item>
                            <a-space>
                                Model:
                                <ModelSelect style="width: 200px" :selected="model" :prefer="options!!.model"
                                    :models="store.globalModels.models ?? []"
                                    v-on:select="(value: string) => { model = value }"
                                    v-on:prefer="(value: string) => updateDefaultModel(value)">
                                </ModelSelect>
                                <a-button @click="reloadModels()">
                                    <template #icon>
                                        <SyncOutlined />
                                    </template>
                                </a-button>
                            </a-space>
                        </a-list-item>

                        <a-list-item>
                            <a-space>
                                Temperature:
                                <a-input-number style="width: 100px" :min="0" :max="2" :step="0.1"
                                    v-model:value="options.temperature" placeholder="key">
                                </a-input-number>
                            </a-space>
                            <a-space>
                                Top_P:
                                <a-input-number style="width: 100px" :min="0" :max="2" :step="0.1"
                                    v-model:value="options.topP" placeholder="key">
                                </a-input-number>
                            </a-space>

                        </a-list-item>

                        <a-list-item>
                            Use Embed
                            <a-switch v-model:checked="withEmbed" @change="(e) => {
                                if (e.target.checked) {
                                    let idx = prompt.plugins!!.findIndex(it => { return it == 'embed' })
                                    if (idx >= 0) {
                                        return
                                    }
                                    prompt.plugins!!.push('embed')
                                }
                            }"></a-switch>

                        </a-list-item>


                        <a-space>
                            <ArgumentPanel :setting="store.globalArgs" :args="args" @select=selectArg>
                            </ArgumentPanel>
                        </a-space>

                    </a-list>

                </a-card>


                <a-card title="Replace Args">

                    <template #extra>
                        <a-button @click="fetchArgument(key)">
                            <template #icon>
                                <SyncOutlined />
                            </template>
                        </a-button>
                    </template>



                    <ArgumentPanel :setting="argSetting" :args="args" @select=selectArg>
                        <template #extra>
                            <a-space direction="horizontal">
                                <a-select ref="select" v-model:value="argKey" style="width: 120px" show-search>
                                    <a-select-option v-for="k in args" :key="k.key">{{ k.key }}</a-select-option>
                                </a-select>

                                <a-input v-model:value="argKey" placeholder="key">
                                </a-input>

                                <a-input v-model:value="argValue" placeholder="value">
                                </a-input>

                                <a-button @click="newArg()">
                                    <template #icon>
                                        <PlusOutlined />
                                    </template>
                                    New
                                </a-button>
                            </a-space>
                            <a-divider></a-divider>

                        </template>
                    </ArgumentPanel>


                </a-card>






            </a-col>
        </a-row>
    </div>
</template>

<script lang="ts" setup>
import { PlusOutlined, SyncOutlined } from '@ant-design/icons-vue';
import { useClipboard } from '@vueuse/core';
import { onMounted, ref } from 'vue';

import { useRoute } from 'vue-router';

import ArgumentPanel from '@/components/ArgumentPanel.vue';
import ModelSelect from '@/components/ModelSelect.vue';
import PromptInput from "@/components/PromptInput.vue";
import { backend, BackendHelper } from "@/scripts/backend";
import { openNotification } from "@/scripts/notice";
import { useConfigStore } from "@/stores/global-config";
import type {
    ArgRequest,
    Argument,
    ArgumentSetting,
    LLMOption,
    Message,
    NewCommitBody,
    Prompt,
    UpdatePromptBody
} from "src/sdk";
import VueMarkdown from 'vue-markdown-render';
import PromptCard from '../components/PromptCard.vue';

const store = useConfigStore()
// use
const r = useRoute()
const { text, copy, copied, isSupported } = useClipboard({})

const key = r.params.key.toString()

const responseMode = ref()


// field
const loading = ref(false)
const model = ref<string>("")



const withEmbed = ref<boolean>(false)

const argValue = ref<string>("")
const argKey = ref<string>("")
const response = ref(<string>"test")
const argSetting = ref<ArgumentSetting>(
    {
        name: "",
        args: []
    }
)
const args = ref<Argument[]>([])
const prompt = ref<Prompt>(<Prompt>{})
const options = ref<LLMOption>(<LLMOption>{})

// created
onMounted(
    () => {
        fetchPrompt(key)
    }
)

function reloadModels() {
    backend.apiGlobalModelsGet()
        .then((res) => {
            store.globalModels = res.data
        })
}



function updateDefaultModel(model: string) {
    options.value.model = model
    let body: UpdatePromptBody = <UpdatePromptBody>({ options: options.value })
    backend.apiPromptNamePut(body, prompt.value.name)
        .then(() => {
            console.log(model)
        })
        .catch(err => {
            openNotification(err, 'error')
        })
}


function selectArg(key: string, value: string) {
    for (const item of args.value) {
        if (item.key == key) {
            item.value = value
            return
        }
    }
    args.value.push({ key: key, value: value, candidates: [] })
}

async function newArg() {
    let body: ArgRequest = {
        key: argKey.value,
        value: argValue.value
    }

    if (argKey.value == "" || argValue.value == "") {
        return
    }

    await backend.apiPromptArgsNamePut(body, key)
        .then(response => {
            selectArg(argKey.value, argValue.value)
        })
        .catch(err => {
            openNotification(err.toString(), "error")
        })

    await fetchArgument(key)

}


// methods
function responseToPrompt() {
    addPrompt(prompt.value.messages.length, 'assistant', response.value)
}

function deletePrompt(index: number) {
    let ms = prompt.value.messages

    ms.splice(index, 1); // 删除指定索引的元素
}



async function doCommit() {
    let body: NewCommitBody = {
        name: key,
        commit: {
            messages: prompt.value.messages,
            response: response.value,
            args: args.value,
            options: options.value,
        },
    }
    backend.apiCommitPost(body)
        .then(() => {

        })
        .catch(err => {
            openNotification(err.toString(), "error")
        })
}

function addPrompt(index: number, role: string, content: string) {
    let m: Message = { content: content, role: role, enable: true, }
    let ms = prompt.value.messages
    while (1) {
        if (ms[index - 1].role == 'system') {
            index -= 1
        } else {
            break
        }
    }

    prompt.value.messages.splice(index, 0, m)

    console.log(prompt.value.messages)
}

function order(index: number, delta: number) {
    let another = index + delta
    console.log('index', index, another)
    if (another < 0 || another >= prompt.value.messages.length) {
        return
    }
    let current = prompt.value.messages[index]
    let next = prompt.value.messages[index + delta]

    prompt.value.messages[index] = next
    prompt.value.messages[index + delta] = current

    console.log(prompt.value.messages)
}


async function fetchArgument(name: string) {
    await backend.apiPromptArgsNameGet(name)
        .then(response => {
            argSetting.value = response.data

            console.log('response', argSetting.value)

        })
        .catch(err => {
            openNotification(err.toString(), "error")
        })

}

async function fetchPrompt(name: string) {
    await fetchArgument(name)

    await backend.apiPromptNameGet(name)
        .then(response => {
            console.log(response.data)
            prompt.value = response.data;

            args.value = prompt.value.args!!
            console.log(args.value)

            options.value = prompt.value.options!!
            console.log(options.value)

            model.value = options.value.model!!
            console.log(model.value)


            let idx = prompt.value.plugins?.findIndex(it => { return it == 'embed' })
            console.info(idx)
            if (idx !== undefined && idx >= 0) {
                withEmbed.value = true
            }
        })
        .catch(err => {
            openNotification(err.toString(), "error")
        })
}

function reload() {
    fetchPrompt(key);
}


async function chat() {
    if (withEmbed.value) {
        await chatWithRAG()
    } else {
        await chatWithPrompt()
    }
}

async function chatWithRAG() {
    try {
        let messages = prompt.value.messages

        console.log(messages)

        // assert(messages[0].role, 'system',"")
        // assert(messages[-1].role, 'user',"")

        // // replace first system prompt
        // await backend.apiActionRetrievePost({ name: key, message: messages[-1].content })
        //     .then((res) => {
        //         messages[0].content = res.data
        //     })


        let body: UpdatePromptBody = {
            messages: prompt.value.messages!!,
            model: model.value,
            args: args.value,
            plugins: [
                'embed'
            ]
        }
        await backend.apiPromptNamePut(body, key).catch((err) => {
            console.log(err)
            openNotification(err.toString(), "error")
        })

        loading.value = true
        response.value = ''

        await backend.apiActionRetrieveGeneratePost(
            {
                name: key,
                messages: messages?.filter((item: Message) => item.enable)
            },
        )
            .then(
                (res) => {
                    response.value = res.data;
                }
            )
    } catch (err) {
        openNotification(err.toString(), "error")
    } finally {
        loading.value = false
    }
}

async function chatWithPrompt() {
    console.log("model", model.value)
    console.log(prompt.value.messages)
    let body: UpdatePromptBody = {
        messages: prompt.value.messages!!,
        args: args.value,
        options: options.value,
    }
    await backend.apiPromptNamePut(body, key).catch((err) => {
        console.log(err)
        openNotification(err.toString(), "error")
    })

    try {
        loading.value = true
        response.value = ''
        await BackendHelper.doChat(options.value, prompt.value.messages, args.value)
            .then(
                (res) => {
                    response.value = res.data;
                }
            )

    } catch (err) {
        console.log(err)
        openNotification(err.toString(), "error")
    } finally {
        loading.value = false
    }
}
</script>
@/stores/global-config

// frontend/v2/src/views/PromptView.tsx
import {
    PlusOutlined,
    SyncOutlined
} from '@ant-design/icons';
import {
    Button,
    Card,
    Col,
    Divider,
    Input,
    InputNumber,
    List,
    Row,
    Select,
    Skeleton,
    Space,
    Switch,
    Tabs,
    Typography
} from 'antd';
import { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { useParams } from 'react-router-dom';

// Assuming these components would be created separately
import ArgumentPanel from '../components/ArgumentPanel';
import ModelSelect from '../components/ModelSelect';
import PromptInput from '../components/PromptInput';

// Utility functions that would replace the Vue backend and notification services
import { backend, BackendHelper } from '../scripts/backend';
import { openNotification } from '../scripts/notice';
import { useConfigStore } from '../stores/global';

const { Title } = Typography;
const { TabPane } = Tabs;
const { Option } = Select;


function PromptView() {
    const { key } = useParams();
    console.log("param:", key);
    const store = useConfigStore();

    // State variables
    const [loading, setLoading] = useState(false);
    const [model, setModel] = useState("");
    const [models, setModels] = useState([]);
    const [timecost, setTimecost] = useState(0);
    const [description, setDescription] = useState("");
    const [withEmbed, setWithEmbed] = useState(false);
    const [argValue, setArgValue] = useState("");
    const [argKey, setArgKey] = useState("");
    const [response, setResponse] = useState("test");
    const [responseMode, setResponseMode] = useState("1");
    const [argSetting, setArgSetting] = useState({});
    const [args, setArgs] = useState([]);
    const [messages, setMessages] = useState([]); // Default empty array for messages
    const [plugins, setPlugins] = useState([]); // Default empty array for plugins
    const [options, setOptions] = useState({}); // Default empty object for options

    // Effects
    useEffect(() => {
        fetchPrompt(key);
        fetchModels();
    }, [key]);

    // Methods
    const copy = (text) => {
        navigator.clipboard.writeText(text).then(() => {
            openNotification('Copied to clipboard', 'success');
        }).catch(err => {
            openNotification('Failed to copy: ' + err, 'error');
        });
    };

    const fetchModels = async () => {
        try {
            const res = await backend.apiGlobalModelsGet();
            console.log("fetch models: ", res.data);
            setModels(res.data.models || []);
        } catch (err) {
            openNotification('Failed to reload models: ' + err.toString(), 'error');
        }
    };

    const updatePreferModel = (modelName) => {
        const newOptions = { ...(options || {}), prefer: modelName }; // 防止 options 为 undefined
        setOptions(newOptions);

        const body = { options: newOptions };
        backend.apiPromptNamePut(body, prompt.name)
            .catch(err => {
                openNotification(err, 'error');
            });
    };

    const selectArg = (key, value) => {
        const newArgs = [...args];
        const existingArg = newArgs.find(item => item.key === key);

        if (existingArg) {
            existingArg.value = value;
        } else {
            newArgs.push({ key, value, candidates: [] });
        }

        setArgs(newArgs);
    };

    const newArg = async () => {
        if (argKey === "" || argValue === "") {
            return;
        }

        const body = {
            key: argKey,
            value: argValue
        };

        try {
            await backend.apiPromptArgsNamePut(body, key);
            selectArg(argKey, argValue);
            await fetchArgument(key);
        } catch (err) {
            openNotification(err.toString(), "error");
        }
    };

    const responseToPrompt = () => {
        addPrompt(messages.length, 'assistant', response);
    };

    const deletePrompt = (index) => {
        const newMessages = [...messages];
        newMessages.splice(index, 1);
        setMessages(newMessages);
    };

    const doCommit = async () => {
        const body = {
            name: key,
            commit: {
                messages: messages,
                response,
                args,
                options,
                timecost,
            },
        };

        try {
            await backend.apiCommitPost(body);
        } catch (err) {
            openNotification(err.toString(), "error");
        }
    };

    const addPrompt = (index, role, content) => {
        const newMessages = [...messages];
        const newMessage = { content, role, enable: true };

        let insertIndex = index;
        while (insertIndex > 0 && newMessages[insertIndex - 1].role === 'system') {
            insertIndex -= 1;
        }

        newMessages.splice(insertIndex, 0, newMessage);
        setMessages(newMessages);
    };

    const order = (index, delta) => {
        const anotherIndex = index + delta;
        if (anotherIndex < 0 || anotherIndex >= messages.length) {
            return;
        }

        const newMessages = [...messages];
        const temp = newMessages[index];
        newMessages[index] = newMessages[anotherIndex];
        newMessages[anotherIndex] = temp;

        setMessages(newMessages);
    };

    const fetchArgument = async (name) => {
        setArgSetting({})
        // try {
        //     const response = await backend.apiPromptArgsNameGet(name);
        //     // setArgSetting(response.data || { name: "", args: [] }); // 确保 response.data 有默认值
        //     setArgSetting({})
        // } catch (err) {
        //     openNotification(err.toString(), "error");
        // }
    };

    const fetchPrompt = async (name) => {
        try {
            await fetchArgument(name);

            const response = await backend.apiPromptNameGet(name);
            const promptData = response.data;

            setMessages(promptData.messages || [],)
            setPlugins(promptData.plugins || [],)
            setDescription(promptData.description || "");
            setArgs(promptData.args || []);
            setOptions(promptData.options || {});
            setModel(promptData.options?.model || "");

            const hasEmbed = (promptData.plugins || []).includes('embed');
            setWithEmbed(hasEmbed);
        } catch (err: any) {
            console.log(err);
            // openNotification("" + err.toString(), "error");
        }
    };

    const reload = () => {
        fetchPrompt(key);
    };

    const update = async () => {
        const body = {
            messages: messages,
            args: args,
            options: options,
            description: description,
        };

        try {
            await backend.apiPromptNamePut(body, key);
        } catch (err) {
            openNotification("" + err.toString(), "error");
        }
    };

    const chat = async () => {
        if (withEmbed) {
            await chatWithRAG();
        } else {
            await chatWithPrompt();
        }
    };

    const chatWithRAG = async () => {
        try {

            const body = {
                messages: messages,
                options: options,
                args: args,
                plugins: ['embed']
            };

            await backend.apiPromptNamePut(body, key);

            setLoading(true);
            setResponse('');

            const res = await backend.apiActionRetrieveGeneratePost({
                name: key,
                messages: messages.filter(item => item.enable)
            });

            setResponse(res.data);
        } catch (err) {
            openNotification("" + err.toString(), "error");

        } finally {
            setLoading(false);
        }
    };

    const chatWithPrompt = async () => {
        try {
            const body = {
                messages: messages,
                args: args,
                options: options,
            };

            await backend.apiPromptNamePut(body, key);

            setLoading(true);
            setResponse('');

            const newOptions = { ...options, model };
            setOptions(newOptions);

            const start = new Date().getTime();
            const res = await BackendHelper.doChat(newOptions, messages, args);
            const end = new Date().getTime();

            setResponse(res.data);
            setTimecost(end - start);
        } catch (err) {
            openNotification(err.toString(), "error");
        } finally {
            setLoading(false);
        }
    };

    const handleEmbedChange = (checked) => {
        setWithEmbed(checked);
        if (checked) {
            const plugins = prompt.plugins || [];
            if (!plugins.includes('embed')) {
                const newPlugins = [...plugins, 'embed'];
                setPrompt({ ...prompt, plugins: newPlugins });
            }
        }
    };

    return (
        <>
            <Space align="center" style={{ width: '100%' }}>
                <Title>{key}</Title>
                <Space direction="horizontal" align="baseline">
                    <Button onClick={reload}>
                        <SyncOutlined />
                    </Button>
                    <Divider type="vertical" />
                </Space>
            </Space>
            <Space>
                <Input style={{ width: 400 }} value={description} onChange={e => setDescription(e.target.value)} />
            </Space>

            <Row gutter={6}>
                <Col span={12}>
                    <Card
                        title="Replace Args"
                        extra={
                            <Button onClick={() => fetchArgument(key)}>
                                <SyncOutlined />
                            </Button>
                        }
                    >
                        <ArgumentPanel
                            setting={argSetting}
                            args={args}
                            onSelect={selectArg}
                            extra={
                                <Space direction="horizontal">
                                    <Select
                                        value={argKey}
                                        style={{ width: 120 }}
                                        showSearch
                                        onChange={value => setArgKey(value)}
                                    >
                                        {args.map(arg => (
                                            <Option key={arg.key} value={arg.key}>{arg.key}</Option>
                                        ))}
                                    </Select>
                                    <Input
                                        value={argKey}
                                        placeholder="key"
                                        onChange={e => setArgKey(e.target.value)}
                                    />
                                    <Input
                                        value={argValue}
                                        placeholder="value"
                                        onChange={e => setArgValue(e.target.value)}
                                    />
                                    <Button onClick={newArg}>
                                        <PlusOutlined />
                                        New
                                    </Button>
                                </Space>
                            }
                        />
                    </Card>

                    <Card
                        title="Prompt"
                        extra={
                            <Space>
                                <Button onClick={() => copy(JSON.stringify({
                                    name: key,
                                    prompt: messages.filter(item => item.enable)
                                }, null, 2))}>
                                    CopyAll
                                </Button>
                                <Divider type="vertical" />
                                <Button onClick={() => {
                                    const newMessages = messages.map(item => ({ ...item, enable: false }));
                                    setMessages(newMessages);
                                }}>
                                    DisableAll
                                </Button>
                                <Button onClick={() => {
                                    const newMessages = messages.map(item => ({ ...item, enable: true }));
                                    setMessages(newMessages)
                                }}>
                                    EnableAll
                                </Button>
                            </Space>
                        }
                    >
                        <PromptInput
                            messages={messages}
                            setMessages={setMessages}
                            withCopy={true}
                            withControl={true}
                            onOrderUp={index => order(index, -1)}
                            onOrderDown={index => order(index, 1)}
                            onRemove={index => deletePrompt(index)}
                            onAdd={(index, role, content) => addPrompt(index, role, content)}
                        />

                        <Divider>
                            <Space>
                                <Button onClick={() => {
                                    const newMessages = [...messages, { role: 'user', enable: true, content: '' }];
                                    setMessages(newMessages);
                                }}>
                                    <PlusOutlined />
                                </Button>
                            </Space>
                        </Divider>
                    </Card>
                </Col>

                <Col span={12}>
                    <Card
                        title="Response"
                        extra={
                            <Space direction="horizontal">
                                <Button onClick={update}>Update</Button>
                                <Button onClick={chat}>Request</Button>
                                <Button onClick={doCommit}>Commit</Button>
                                <Button onClick={() => copy(response)}>Copy</Button>
                                <Button onClick={responseToPrompt}>Append</Button>
                            </Space>
                        }
                    >
                        <Skeleton loading={loading} active>
                            <div>
                                <Typography.Text>time cost: {timecost / 1000} second</Typography.Text>
                                <Divider />
                                <Tabs
                                    activeKey={responseMode}
                                    onChange={key => setResponseMode(key)}
                                    items={[
                                        {
                                            key: "1",
                                            label: "Markdown",
                                            children: <ReactMarkdown>{response}</ReactMarkdown>
                                        },
                                        {
                                            key: "2",
                                            label: "Text",
                                            children: (
                                                <Input.TextArea
                                                    value={response}
                                                    onChange={e => setResponse(e.target.value)}
                                                    autoSize={{ minRows: 3 }}
                                                    style={{ width: '100%' }}
                                                />
                                            ),
                                            forceRender: true
                                        }
                                    ]}
                                />
                            </div>
                        </Skeleton>
                    </Card>

                    <Card title="LLM Options">
                        <List itemLayout="horizontal">
                            <List.Item>
                                <Space>
                                    Model:
                                    <ModelSelect
                                        style={{ width: 200 }}
                                        selected={model}
                                        prefer={options?.prefer}
                                        models={models}
                                        onSelect={value => setModel(value)}
                                        onPrefer={value => updatePreferModel(value)}
                                    />
                                    <Button onClick={fetchModels}>
                                        <SyncOutlined />
                                    </Button>
                                </Space>
                            </List.Item>

                            <List.Item>
                                <Space>
                                    Temperature:
                                    <InputNumber
                                        style={{ width: 100 }}
                                        min={0}
                                        max={2}
                                        step={0.1}
                                        value={options.temperature}
                                        onChange={value => setOptions({ ...options, temperature: value })}
                                    />
                                </Space>
                                <Space>
                                    Top_P:
                                    <InputNumber
                                        style={{ width: 100 }}
                                        min={0}
                                        max={2}
                                        step={0.1}
                                        value={options.topP}
                                        onChange={value => setOptions({ ...options, topP: value })}
                                    />
                                </Space>
                            </List.Item>

                            <List.Item>
                                Use Embed
                                <Switch
                                    checked={withEmbed}
                                    onChange={handleEmbedChange}
                                />
                            </List.Item>

                            <Space>
                                <ArgumentPanel
                                    setting={store.globalArgs}
                                    args={args}
                                    onSelect={selectArg}
                                />
                            </Space>
                        </List>
                    </Card>
                </Col>
            </Row>
        </>
    );
}

export default PromptView;
