// web2/src/views/IndexView.tsx
import React, { useEffect, useState } from 'react';
import { Card, Space, Input, Button, Divider, Modal, List, Typography } from 'antd';
import { EditFilled, SyncOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { backend } from "../scripts/backend";

const IndexView: React.FC = () => {
    const navigate = useNavigate();
    const [group, setGroup] = useState<Record<string, string[]>>({ "": [] });
    const [open, setOpen] = useState(false);
    const [sourceKey, setSourceKey] = useState("");
    const [targetKey, setTargetKey] = useState("");
    const [newName, setNewName] = useState("");
    const [newGroup, setNewGroup] = useState("");

    useEffect(() => {
        fetchList(false);
    }, []);

    const showModal = (item: string) => {
        setOpen(true);
        setSourceKey(item);
        setTargetKey(item);
    };

    const handleOk = () => {
        setOpen(false);
        backend.apiActionRenamePost({
            source: sourceKey,
            target: targetKey
        });
    };

    const openPrompt = (key: string) => {
        navigate(`/view/prompt/${key}`);
    };

    const create_profile = async (group: string, name: string) => {
        await backend.apiPromptPost({group: group}, name);
        fetchList(true);
    };

    const fetchList = async (refresh: boolean) => {
        try {
            const response = await backend.apiPromptGet(refresh);
            setGroup(response.data.data);
            console.log(response.data);
            return response.data;
        } catch (error) {
            console.error(error);
        }
    };

    return (
        <Card title="Project List">
            <Space direction="horizontal">
                <Input 
                    value={newGroup}
                    onChange={(e) => setNewGroup(e.target.value)}
                    placeholder="group name"
                    size="large"
                />
                <Input 
                    value={newName}
                    onChange={(e) => setNewName(e.target.value)}
                    placeholder="prompt name"
                    size="large"
                />
                <Button onClick={() => create_profile(newGroup, newName)}>
                    Create
                </Button>
                <Button onClick={() => fetchList(true)}>
                    <SyncOutlined />
                </Button>
            </Space>

            <Divider />

            {Object.entries(group).map(([key, values]) => (
                <Card key={key} title={key || '[default]'}>
                    <Space direction="horizontal">
                        <Input 
                            value={newName}
                            onChange={(e) => setNewName(e.target.value)}
                            placeholder="prompt name"
                        />
                        <Button onClick={() => create_profile(key, newName)}>
                            Create In Group
                        </Button>
                    </Space>

                    <Divider />
                    
                    <Modal
                        open={open}
                        title="Rename"
                        onOk={handleOk}
                        onCancel={() => setOpen(false)}
                    >
                        <p>source name: {sourceKey}</p>
                        <p>
                            target name:
                            <Input 
                                value={targetKey}
                                onChange={(e) => setTargetKey(e.target.value)}
                            />
                        </p>
                    </Modal>

                    <List
                        dataSource={[...values].sort()}
                        grid={{ gutter: 16, column: 4 }}
                        size="small"
                        renderItem={(item) => (
                            <List.Item>
                                <Space>
                                    <Button type="primary" onClick={() => showModal(item)}>
                                        <EditFilled />
                                    </Button>
                                    <Typography.Link 
                                        className="large-font"
                                        onClick={() => openPrompt(item)}
                                    >
                                        {item}
                                    </Typography.Link>
                                </Space>
                            </List.Item>
                        )}
                    />
                </Card>
            ))}
        </Card>
    );
};

export default IndexView;

// promptly-vue/src/views/IndexView.vue
<style scoped>
.large-font {
    font-size: 200%
}
</style>

<template>
    <a-card title="Project List">
        <a-space direction="horizontal">


            <a-input-search v-model:value="store.source.name" placeholder="input search text" size="large"
                @search="create_profile">
                <template #enterButton>
                    <a-button>Create</a-button>
                </template>
            </a-input-search>

            <a-button @click="fetchList(true)">
                <template #icon>
                    <SyncOutlined></SyncOutlined>
                </template>
            </a-button>


        </a-space>

        <a-divider></a-divider>

        <a-list :data-source="keys" size="small" :grid="{ gutter: 16, column: 4 }">
            <template #renderItem="{ item }">
                <a-list-item>
                    <a-typography-link class="large-font" @click="openPrompt(item)">
                        {{ item }}
                    </a-typography-link>
                </a-list-item>
            </template>
        </a-list>
    </a-card>
</template>

<script lang="ts" setup>
import router from "@/router";

import { ApiFactory } from "@/scripts/api";
import { useSnapshotStore } from "@/stores/snapshot";
import { SyncOutlined } from "@ant-design/icons-vue";
import { onMounted, ref } from 'vue';

const api = ApiFactory()

// field
const keys = ref([
    '1', '2', '3'
])


const store = useSnapshotStore()

// created
onMounted(
    () => {
        fetchList(false)
    }
)


function openPrompt(key: string) {
    router.push(`/view/prompt/${key}`)
}


async function create_profile(name: string) {
    await api.apiPromptPut(name)
    fetchList(true)
}


async function fetchList(refresh: boolean) {
    return api.apiListPromptGet(refresh).then(
        response => {
            console.log(response.data)
            keys.value = response.data.keys
            keys.value.sort()
            return response.data
        }
    ).catch(
        error => {
            console.error(error)
        }
    )
}

</script>
