// web2/src/views/PromptView.tsx
import {
    PlusOutlined,
    SyncOutlined
} from '@ant-design/icons';
import {
    Button,
    Card,
    Col,
    Collapse,
    Divider,
    Input,
    InputNumber,
    List,
    Row,
    Select,
    Skeleton,
    Space,
    Switch,
    Tabs,
    Typography
} from 'antd';
import { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { useParams } from 'react-router-dom';

// Assuming these components would be created separately
import ArgumentPanel from '../components/ArgumentPanel';
import ModelSelect from '../components/ModelSelect';
import PromptInput from '../components/PromptInput';

// Utility functions that would replace the Vue backend and notification services
import { backend, BackendHelper } from '../scripts/backend';
import { openNotification } from '../scripts/notice';
import { useConfigStore } from '../stores/global';

const { Title } = Typography;
const { Panel } = Collapse;
const { TabPane } = Tabs;
const { Option } = Select;

// CSS classes
const styles = {
    scrollShort: {
        height: '200px',
        overflow: 'auto',
    }
};

function PromptView() {
    const { key } = useParams();
    const store = useConfigStore();

    // State variables
    const [loading, setLoading] = useState(false);
    const [model, setModel] = useState("");
    const [timecost, setTimecost] = useState(0);
    const [description, setDescription] = useState("");
    const [withEmbed, setWithEmbed] = useState(false);
    const [argValue, setArgValue] = useState("");
    const [argKey, setArgKey] = useState("");
    const [response, setResponse] = useState("test");
    const [responseMode, setResponseMode] = useState("1");
    const [argSetting, setArgSetting] = useState({ name: "", args: [] });
    const [args, setArgs] = useState([]);
    const [prompt, setPrompt] = useState({ messages: [] });
    const [options, setOptions] = useState({});

    // Effects
    useEffect(() => {
        fetchPrompt(key);
    }, [key]);

    // Methods
    const copy = (text) => {
        navigator.clipboard.writeText(text).then(() => {
            openNotification('Copied to clipboard', 'success');
        }).catch(err => {
            openNotification('Failed to copy: ' + err, 'error');
        });
    };

    const reloadModels = async () => {
        try {
            const res = await backend.apiGlobalModelsGet();
            store.setGlobalModels(res.data);
        } catch (err) {
            openNotification(err.toString(), 'error');
        }
    };

    const updatePreferModel = (modelName) => {
        const newOptions = { ...options, prefer: modelName };
        setOptions(newOptions);

        const body = { options: newOptions };
        backend.apiPromptNamePut(body, prompt.name)
            .catch(err => {
                openNotification(err, 'error');
            });
    };

    const selectArg = (key, value) => {
        const newArgs = [...args];
        const existingArg = newArgs.find(item => item.key === key);

        if (existingArg) {
            existingArg.value = value;
        } else {
            newArgs.push({ key, value, candidates: [] });
        }

        setArgs(newArgs);
    };

    const newArg = async () => {
        if (argKey === "" || argValue === "") {
            return;
        }

        const body = {
            key: argKey,
            value: argValue
        };

        try {
            await backend.apiPromptArgsNamePut(body, key);
            selectArg(argKey, argValue);
            await fetchArgument(key);
        } catch (err) {
            openNotification(err.toString(), "error");
        }
    };

    const responseToPrompt = () => {
        addPrompt(prompt.messages.length, 'assistant', response);
    };

    const deletePrompt = (index) => {
        const newMessages = [...prompt.messages];
        newMessages.splice(index, 1);
        setPrompt({ ...prompt, messages: newMessages });
    };

    const doCommit = async () => {
        const body = {
            name: key,
            commit: {
                messages: prompt.messages,
                response,
                args,
                options,
                timecost,
            },
        };

        try {
            await backend.apiCommitPost(body);
        } catch (err) {
            openNotification(err.toString(), "error");
        }
    };

    const addPrompt = (index, role, content) => {
        const newMessages = [...prompt.messages];
        const newMessage = { content, role, enable: true };

        let insertIndex = index;
        while (insertIndex > 0 && newMessages[insertIndex - 1].role === 'system') {
            insertIndex -= 1;
        }

        newMessages.splice(insertIndex, 0, newMessage);
        setPrompt({ ...prompt, messages: newMessages });
    };

    const order = (index, delta) => {
        const anotherIndex = index + delta;
        if (anotherIndex < 0 || anotherIndex >= prompt.messages.length) {
            return;
        }

        const newMessages = [...prompt.messages];
        const temp = newMessages[index];
        newMessages[index] = newMessages[anotherIndex];
        newMessages[anotherIndex] = temp;

        setPrompt({ ...prompt, messages: newMessages });
    };

    const fetchArgument = async (name) => {
        try {
            const response = await backend.apiPromptArgsNameGet(name);
            setArgSetting(response.data);
        } catch (err) {
            openNotification(err.toString(), "error");
        }
    };

    const fetchPrompt = async (name) => {
        try {
            await fetchArgument(name);

            const response = await backend.apiPromptNameGet(name);
            const promptData = response.data;

            setPrompt(promptData);
            setDescription(promptData.description || "");
            setArgs(promptData.args || []);
            setOptions(promptData.options || {});
            setModel(promptData.options?.model || "");

            const hasEmbed = promptData.plugins?.includes('embed');
            setWithEmbed(hasEmbed);
        } catch (err) {
            openNotification(err.toString(), "error");
        }
    };

    const reload = () => {
        fetchPrompt(key);
    };

    const update = async () => {
        const body = {
            messages: prompt.messages,
            args: args,
            options: options,
            description: description,
        };

        try {
            await backend.apiPromptNamePut(body, key);
        } catch (err) {
            openNotification(err.toString(), "error");
        }
    };

    const chat = async () => {
        if (withEmbed) {
            await chatWithRAG();
        } else {
            await chatWithPrompt();
        }
    };

    const chatWithRAG = async () => {
        try {
            const messages = prompt.messages;

            const body = {
                messages: prompt.messages,
                options: options,
                args: args,
                plugins: ['embed']
            };

            await backend.apiPromptNamePut(body, key);

            setLoading(true);
            setResponse('');

            const res = await backend.apiActionRetrieveGeneratePost({
                name: key,
                messages: messages.filter(item => item.enable)
            });

            setResponse(res.data);
        } catch (err) {
            openNotification(err.toString(), "error");
        } finally {
            setLoading(false);
        }
    };

    const chatWithPrompt = async () => {
        try {
            const body = {
                messages: prompt.messages,
                args: args,
                options: options,
            };

            await backend.apiPromptNamePut(body, key);

            setLoading(true);
            setResponse('');

            const newOptions = { ...options, model };
            setOptions(newOptions);

            const start = new Date().getTime();
            const res = await BackendHelper.doChat(newOptions, prompt.messages, args);
            const end = new Date().getTime();

            setResponse(res.data);
            setTimecost(end - start);
        } catch (err) {
            openNotification(err.toString(), "error");
        } finally {
            setLoading(false);
        }
    };

    const handleEmbedChange = (checked) => {
        setWithEmbed(checked);
        if (checked) {
            const plugins = prompt.plugins || [];
            if (!plugins.includes('embed')) {
                const newPlugins = [...plugins, 'embed'];
                setPrompt({ ...prompt, plugins: newPlugins });
            }
        }
    };

    return (
        <div>
            <Space align="center" style={{ width: '100%' }}>
                <Title>{key}</Title>
                <Space direction="horizontal" align="baseline">
                    <Button onClick={reload}>
                        <SyncOutlined />
                    </Button>
                    <Divider type="vertical" />
                </Space>
            </Space>
            <Space>
                <Input style={{ width: 400 }} value={description} onChange={e => setDescription(e.target.value)} />
            </Space>

            <Row gutter={6}>
                <Col span={12}>
                    <Card
                        title="Replace Args"
                        extra={
                            <Button onClick={() => fetchArgument(key)}>
                                <SyncOutlined />
                            </Button>
                        }
                    >
                        <ArgumentPanel
                            setting={argSetting}
                            args={args}
                            onSelect={selectArg}
                            extra={
                                <Space direction="horizontal">
                                    <Select
                                        value={argKey}
                                        style={{ width: 120 }}
                                        showSearch
                                        onChange={value => setArgKey(value)}
                                    >
                                        {args.map(arg => (
                                            <Option key={arg.key} value={arg.key}>{arg.key}</Option>
                                        ))}
                                    </Select>
                                    <Input
                                        value={argKey}
                                        placeholder="key"
                                        onChange={e => setArgKey(e.target.value)}
                                    />
                                    <Input
                                        value={argValue}
                                        placeholder="value"
                                        onChange={e => setArgValue(e.target.value)}
                                    />
                                    <Button onClick={newArg}>
                                        <PlusOutlined />
                                        New
                                    </Button>
                                </Space>
                            }
                        />
                    </Card>

                    <Card
                        title="Prompt"
                        extra={
                            <Space>
                                <Button onClick={() => copy(JSON.stringify({
                                    name: key,
                                    prompt: prompt.messages.filter(item => item.enable)
                                }, null, 2))}>
                                    CopyAll
                                </Button>
                                <Divider type="vertical" />
                                <Button onClick={() => {
                                    const newMessages = prompt.messages.map(item => ({ ...item, enable: false }));
                                    setPrompt({ ...prompt, messages: newMessages });
                                }}>
                                    DisableAll
                                </Button>
                                <Button onClick={() => {
                                    const newMessages = prompt.messages.map(item => ({ ...item, enable: true }));
                                    setPrompt({ ...prompt, messages: newMessages });
                                }}>
                                    EnableAll
                                </Button>
                            </Space>
                        }
                    >
                        <Row justify="space-around">
                            <PromptInput
                                messages={prompt.messages}
                                withCopy={true}
                                withControl={true}
                                onOrderUp={index => order(index, -1)}
                                onOrderDown={index => order(index, 1)}
                                onRemove={index => deletePrompt(index)}
                                onAdd={(index, role, content) => addPrompt(index, role, content)}
                            />
                        </Row>

                        <Divider>
                            <Space>
                                <Button onClick={() => {
                                    const newMessages = [...prompt.messages, { role: 'system', enable: true, content: '' }];
                                    setPrompt({ ...prompt, messages: newMessages });
                                }}>
                                    <PlusOutlined />
                                </Button>
                            </Space>
                        </Divider>
                    </Card>
                </Col>

                <Col span={12}>
                    <Card
                        title="Response"
                        extra={
                            <Space direction="horizontal">
                                <Button onClick={update}>Update</Button>
                                <Button onClick={chat}>Request</Button>
                                <Button onClick={doCommit}>Commit</Button>
                                <Button onClick={() => copy(response)}>Copy</Button>
                                <Button onClick={responseToPrompt}>Append</Button>
                            </Space>
                        }
                    >
                        <Skeleton loading={loading} active avatar>
                            <div>
                                <Typography.Text>time cost: {timecost / 1000} second</Typography.Text>
                                <Divider />
                                <Tabs activeKey={responseMode} onChange={key => setResponseMode(key)}>
                                    <TabPane key="1" tab="Markdown">
                                        <ReactMarkdown>{response}</ReactMarkdown>
                                    </TabPane>
                                    <TabPane key="2" tab="Text" forceRender>
                                        <Input.TextArea
                                            value={response}
                                            onChange={e => setResponse(e.target.value)}
                                            autoSize={{ maxRows: 16 }}
                                        />
                                    </TabPane>
                                </Tabs>
                            </div>
                        </Skeleton>
                    </Card>

                    <Card title="LLM Options">
                        <List itemLayout="horizontal">
                            <List.Item>
                                <Space>
                                    Model:
                                    <ModelSelect
                                        style={{ width: 200 }}
                                        selected={model}
                                        prefer={options?.prefer}
                                        models={store.globalModels?.models || []}
                                        onSelect={value => setModel(value)}
                                        onPrefer={value => updatePreferModel(value)}
                                    />
                                    <Button onClick={reloadModels}>
                                        <SyncOutlined />
                                    </Button>
                                </Space>
                            </List.Item>

                            <List.Item>
                                <Space>
                                    Temperature:
                                    <InputNumber
                                        style={{ width: 100 }}
                                        min={0}
                                        max={2}
                                        step={0.1}
                                        value={options.temperature}
                                        onChange={value => setOptions({ ...options, temperature: value })}
                                    />
                                </Space>
                                <Space>
                                    Top_P:
                                    <InputNumber
                                        style={{ width: 100 }}
                                        min={0}
                                        max={2}
                                        step={0.1}
                                        value={options.topP}
                                        onChange={value => setOptions({ ...options, topP: value })}
                                    />
                                </Space>
                            </List.Item>

                            <List.Item>
                                Use Embed
                                <Switch
                                    checked={withEmbed}
                                    onChange={handleEmbedChange}
                                />
                            </List.Item>

                            <Space>
                                <ArgumentPanel
                                    setting={store.globalArgs}
                                    args={args}
                                    onSelect={selectArg}
                                />
                            </Space>
                        </List>
                    </Card>
                </Col>
            </Row>
        </div>
    );
}

export default PromptView;

// promptly-vue/src/views/PromptView.vue
<style>
.scroll-short {
    height: 200px;
    /* 设置组件容器的固定高度 */
    overflow: auto;
    /* 设置溢出部分自动滚动 */
}
</style>

<template>
    <div>
        <a-typography-title>{{ key }}</a-typography-title>
        <a-row :gutter='6'>
            <a-col class="gutter-row" :span="12">

                <a-collapse>
                    <a-collapse-panel header="History">
                        <a-space direction="horizontal" align="baseline" v-for="h in prompt.history">
                            <a-button @click="copy(h)">
                                <template #icon>
                                    <CopyOutlined />
                                </template>
                            </a-button>
                            <p>{{ h }}</p>
                            <!-- <a-textarea v-bind="h"> </a-textarea> -->


                            <!-- <button v-on:click="setContent(item.index, h)">Set</button> -->

                        </a-space>
                    </a-collapse-panel>
                </a-collapse>

                <a-card title="Argument">
                    <CaseInput :setting="argSetting" :args="args" @select="(key, value) => { args.set(key, value) }">
                        <template #extra>
                            <a-row justify="center">
                                <a-space direction="horizontal">
                                    <a-input v-model:value="argKey">
                                    </a-input>

                                    <a-input v-model:value="argValue">
                                    </a-input>

                                    <a-button @click="newArg()">
                                        <template #icon>
                                            <PlusOutlined />
                                        </template>
                                        New
                                    </a-button>
                                </a-space>

                            </a-row>
                            <a-row justify="center">
                                <a-space direction="horizontal">

                                    <a-button @click="saveArgs()">
                                        <template #icon>
                                            <SaveOutlined />
                                        </template>
                                        Save
                                    </a-button>
                                    <a-button @click="cleanArgs()">
                                        <template #icon>
                                            <SyncOutlined />
                                        </template>
                                        Clean
                                    </a-button>
                                </a-space>
                            </a-row>
                        </template>
                    </CaseInput>
                </a-card>

                <a-divider></a-divider>


                <a-card title="Prompt">
                    <a-row justify="end">
                        <a-button @click="() => { prompt.messages.forEach((item) => item.enable = false) }">Disable
                            All
                        </a-button>
                        <a-button @click="() => { prompt.messages.forEach((item) => item.enable = true) }">Enable
                            All
                        </a-button>
                    </a-row>

                    <a-row justify="space-around">
                        <PromptInput :messages="prompt.messages" with-copy with-control
                            @order-up="index => order(index, -1)" @order-down="index => order(index, 1)"
                            @remove="index => deletePrompt(index)" @add="index => addPrompt(index, '')">
                        </PromptInput>
                    </a-row>

                    <a-divider>
                        <a-space>
                            <a-button @click="() => prompt.messages.push({})">
                                <template #icon>
                                    <PlusOutlined />
                                </template>
                            </a-button>
                        </a-space>

                    </a-divider>

                </a-card>

            </a-col>


            <a-col class="gutter-row" :span="12">


                <a-collapse>

                    <a-collapse-panel header="Prompt Preview">
                        <PromptCard :messages="prompt.messages.filter((i) => i.enable)"></PromptCard>
                    </a-collapse-panel>
                </a-collapse>


                <a-card title="Operation">
                    <a-space direction="vertical">
                        <a-space direction="horizontal">
                            <a-button @click="chat">Request</a-button>
                            <a-button @click="commit">Commit</a-button>
                            <a-button @click="reload">Reload</a-button>
                            <a-button @click="gotoTesting">Goto Testing</a-button>
                            <a-button @click="gotoCommit">Goto Commit</a-button>
                        </a-space>

                    </a-space>
                </a-card>

                <a-card title="Corresponding Response">
                    <a-skeleton :loading="loading" active avatar>
                        <div>
                            <a-space direction="horizontal">
                                <a-button>Good</a-button>
                                <a-button>Bad</a-button>
                            </a-space>

                            <a-divider type="vertical"></a-divider>

                            <a-space>
                                <a-button @click="sendToPrompt">Append to prompt</a-button>
                            </a-space>

                            <a-divider></a-divider>

                            <a-textarea v-model:value="response" :auto-size="{ minRows: 20 }"
                                placeholder="textarea with clear icon" allow-clear />
                        </div>
                    </a-skeleton>

                </a-card>

            </a-col>
        </a-row>
    </div>
</template>

<script lang="ts" setup>
import { useClipboard } from '@vueuse/core';
import { ref } from 'vue';

import { CopyOutlined, PlusOutlined, SaveOutlined, SyncOutlined } from '@ant-design/icons-vue';

import { useRoute } from 'vue-router';

import { useSnapshotStore } from '@/stores/snapshot';

import CaseInput from '@/components/CaseInput.vue';
import PromptInput from "@/components/PromptInput.vue";
import { ApiFactory, ApiHelper } from "@/scripts/api";
import { RouteHelper } from '@/scripts/router';
import type { NotificationPlacement } from "ant-design-vue";
import { notification } from 'ant-design-vue';
import type { ArgRequest, ArgumentSetting, CommitItem, Message } from "../../sdk";
import PromptCard from '../components/PromptCard.vue';

const [notification_api, contextHolder] = notification.useNotification();

// use
const store = useSnapshotStore()
const r = useRoute()
const { text, copy, copied, isSupported } = useClipboard({})
const api = ApiFactory()
const key = r.params.key.toString()

// props
const props = defineProps<{
}>()

// field
console.log(store.source.args)

const loading = ref(false)

const argValue = ref<string>("")
const argKey = ref<string>("")
const response = ref(<string>"")
const argSetting = ref<ArgumentSetting>(
    {
        name: "",
        args: {}
    }
)
const args = ref<Map<string, string>>(new Map())
const prompt = ref(
    {
        "history": [],
        "messages": <Message[]>[
            { role: "角色1", content: "内容1", enable: true },
            // 其他数据项
        ],
    }
)

// created
const create = (() => {
    fetchProfile(key)
})()


function newArg() {
    let body: ArgRequest = {
        key: argKey.value,
        value: argValue.value
    }

    if (argKey.value == "" || argValue.value == "") {
        return
    }

    api.apiPromptArgPost(body, key)
        .then(response => {

            if (!argSetting.value.args!![argKey.value]) {
                argSetting.value.args!![argKey.value] = []
            }

            let array = argSetting.value.args!![argKey.value]
            array.push(argValue.value)
        })
}

function cleanArgs() {
    argSetting.value = argSetting.value.filter(item => item.key != '' && item.value != '')
    console.log(argSetting.value)
}

function saveArgs() {
    api.apiPromptArgsPost(argSetting.value)
}


// methods
function sendToPrompt() {
    addPrompt(prompt.value.messages[prompt.value.messages.length - 1].index, response.value)
}

function deletePrompt(index: number) {
    let ms = prompt.value.messages

    ms.splice(index, 1); // 删除指定索引的元素
}

function gotoCommit() {
    console.log(key)

    store.sendSource(key, prompt.value.messages, [])
    RouteHelper.toCommit(key)
}

function gotoTesting() {
    store.sendSource(key, prompt.value.messages, [])
    RouteHelper.toTesting(key)
}


async function commit() {


    let commit: CommitItem = {
        messages: prompt.value.messages,
        response: response.value
    }
    api.apiCommitPost(commit, key,).then(() => {

    })

}

function addPrompt(index: number, content: string) {
    let m: Message = { content: content, role: 'user', enable: true, }
    prompt.value.messages.splice(index, 0, [m])

    console.log(prompt.value.messages)
}

function order(index: number, delta: number) {
    let another = index + delta
    console.log('index', index, another)
    if (another < 0 || another >= prompt.value.messages.length) {
        return
    }
    let current = prompt.value.messages[index]
    let next = prompt.value.messages[index + delta]

    prompt.value.messages[index] = next
    prompt.value.messages[index + delta] = current

    console.log(prompt.value.messages)
}


async function fetchProfile(key: string) {
    await api.apiPromptArgsGet(key)
        .then(response => {
            argSetting.value = response.data

            console.log('response', argSetting.value)

            let tmp = argSetting.value.args
            for (let key in tmp) {
                if (tmp.hasOwnProperty(key)) {
                    const values = tmp[key];
                    console.log(tmp, key, values)
                    args.value.set(key, values[0])
                }
            }
        }).catch(error => {
            console.log(error)
        })

    console.log(args.value)

    await api.apiPromptGet(key)
        .then(response => {
            console.log(response.data)
            prompt.value = response.data;
        })
        .catch(error => {
            console.error(error);
            return null;
        });
}

function reload() {
    fetchProfile(key);
}


function openNotification(message: string, status: string) {
    let placement: NotificationPlacement = 'bottomRight'
    notification[status]({
        message: status,
        description: message,
        placement,
    });
}

async function chat() {

    console.log(prompt.value.messages)
    await api.apiPromptPost(prompt.value.messages, key)

    let argList = []
    for (const [key, value] of args.value) {
        argList.push({ key: key, value: value })
    }

    console.log("arg list", argList)

    loading.value = true

    response.value = ''
    let res = await ApiHelper.doChat(key, prompt.value.messages, argList)
    response.value = res.data;

    loading.value = false
}
</script>
