// web/src/components/ArgumentPanel.vue
<script setup lang="ts">
import type { Argument, ArgumentSetting } from '@/sdk/models';

export interface Props {
    setting: ArgumentSetting,
    args: Argument[],
    mask: string[],
}

const props = withDefaults(
    defineProps<Props>(),
    {
        args: () => new Array<Argument>(),
        mask: () => new Array<string>()
    }
)

console.log(props.setting)

const emit = defineEmits<{
    (e: 'select', key: string, value: string): void
}>()

function onSelect(key, value) {
    console.log(key, value)
    emit('select', key, value)
}

function data() {
    return [{ key: 1, values: 2 }]
    return Object.keys(props.setting.args!!.keys).map(key => {
        return {
            key: key,
            values: props.setting.args!![key]
        }
    }
    )
}

function isDisable(key: string) {
    console.log(props.mask)

    // if (props.mask.findIndex(key) >= 0) {
    //     return true
    // }

    return false
}


const columns = [
    {
        name: 'Key',
        dataIndex: 'key',
        key: 'key',
    },
    {
        title: 'Age',
        dataIndex: 'values',
        key: 'values',
    },
    {
        title: 'Action',
        key: 'action',
    },
];

function getSelect(key: string) {
    for (const item of props.args) {
        if (item.key == key) {
            return item.value
        }
    }
    return ""
}

</script>

<template>
    <a-list item-layout="horizontal">
        <!-- <a-table :columns="columns" :data-source="data"> -->
        <!-- </a-table> -->
        <slot name="extra"></slot>

        <a-list-item v-for="(arg, index) in  setting.args " :key="index">

            <a-space direction="horizontal" align="baseline">
                <a-typography-text>
                    {{ arg.key }}
                </a-typography-text>

                <a-select :disabled="isDisable(arg.key)" ref="select" :value="getSelect(arg.key)" style="width: 300px"
                    @select="(value, option) => onSelect(arg.key, value)">

                    <a-select-option :key="''">
                    </a-select-option>

                    <a-select-option v-for=" (v, index) in arg.candidates" :key="v">
                        <a-popover :title="v">
                            <template #content>
                                <p> {{ v }}</p>
                            </template>
                            {{ v }}
                        </a-popover>

                    </a-select-option>

                </a-select>

            </a-space>

        </a-list-item>

    </a-list>

</template>

<style scoped></style>

// web2/src/components/ArgumentPanel.tsx
import React, { useEffect, useState } from 'react';

interface Argument {
    key: string;
    value: string;
}

interface ArgumentSetting {
    args: Record<string, string[]>;
}

interface Props {
    setting: ArgumentSetting;
    args: Argument[];
    mask: string[];
    onSelect: (key: string, value: string) => void;
}

const ArgumentPanel: React.FC<Props> = ({ setting, args, mask, onSelect }) => {
    const [selectedValues, setSelectedValues] = useState<Record<string, string>>({});

    useEffect(() => {
        // Update the selected values state based on the initial args
        const initialSelected: Record<string, string> = {};
        args.forEach(arg => {
            initialSelected[arg.key] = arg.value;
        });
        setSelectedValues(initialSelected);
    }, [args]);

    const handleSelect = (key: string, value: string) => {
        console.log(key, value);
        setSelectedValues((prev) => ({ ...prev, [key]: value }));
        onSelect(key, value);
    };

    const isDisabled = (key: string) => {
        return mask.includes(key);
    };

    const getSelectValue = (key: string) => {
        return selectedValues[key] || '';
    };

    const data = Object.keys(setting.args || {}).map((key) => ({
        key: key,
        values: setting.args[key],
    }));

    return (
        <div>
            <ul style={{ listStyleType: 'none' }}>
                {data.map((item) => (
                    <li key={item.key} style={{ marginBottom: '20px' }}>
                        <div style={{ display: 'flex', alignItems: 'baseline' }}>
                            <span style={{ marginRight: '10px' }}>{item.key}</span>

                            <select
                                disabled={isDisabled(item.key)}
                                value={getSelectValue(item.key)}
                                onChange={(e) => handleSelect(item.key, e.target.value)}
                                style={{ width: '300px' }}
                            >
                                <option key="" value="">
                                    Select
                                </option>
                                {item.values.map((v, index) => (
                                    <option key={v} value={v}>
                                        {v}
                                    </option>
                                ))}
                            </select>
                        </div>
                    </li>
                ))}
            </ul>
        </div>
    );
};

export default ArgumentPanel;
