// frontend/v1/src/components/ModelSelect.vue
<script setup lang="ts">
import { HeartOutlined, HeartTwoTone } from "@ant-design/icons-vue";


interface Props {
    selected: string,
    prefer: string,
    models: string[],
}

const props = withDefaults(defineProps<Props>(), {
    model: "",
    prefer: "",
    models: () => [],
})


const emit = defineEmits<{
    (e: 'select', value: string): void
    (e: 'prefer', value: string): void

}>()

function onSelect(value: string) {
    console.log(value)
    emit('select', value)
}

function onDefault(value: string) {
    console.log(value)
    emit('prefer', value)
}

</script>

<template>
    <div>
        <a-select style="width: 200px" ref="select" v-model:value="props.selected" @change="onSelect">
            <a-select-option v-for="(value, key)  in models" :value="value">
                <a-button @click="onDefault(value)">
                    <template #icon>
                        <HeartTwoTone v-if="value == prefer" two-tone-color="#eb2f96" />
                        <HeartOutlined v-else />
                    </template>
                </a-button>
                {{ value }}
            </a-select-option>

        </a-select>
    </div>
</template>

<style scoped></style>

// web2/src/components/ModelSelect.tsx
import React, { useState } from 'react';
import { Select, Button } from 'antd';
import { HeartOutlined, HeartTwoTone } from '@ant-design/icons';

interface Props {
    selected: string;
    prefer: string;
    models: string[];
    onSelect: (value: string) => void;
    onPrefer: (value: string) => void;
}

const ModelSelect: React.FC<Props> = ({ selected, prefer, models, onSelect, onPrefer }) => {
    const handleSelect = (value: string) => {
        console.log(value);
        onSelect(value);
    };

    const handleDefault = (value: string) => {
        console.log(value);
        onPrefer(value);
    };

    return (
        <div>
            <Select
                style={{ width: 200 }}
                value={selected}
                onChange={handleSelect}
            >
                {models.map((value) => (
                    <Select.Option key={value} value={value}>
                        <Button onClick={() => handleDefault(value)}>
                            {value === prefer ? (
                                <HeartTwoTone twoToneColor="#eb2f96" />
                            ) : (
                                <HeartOutlined />
                            )}
                        </Button>
                        {value}
                    </Select.Option>
                ))}
            </Select>
        </div>
    );
};

export default ModelSelect;
