// frontend/v2/src/components/PromptCard.tsx
import { Button, Space } from 'antd';
import React from 'react';
import { useClipboard } from 'react-use-clipboard'; // or any other clipboard hook you prefer

interface Message {
    role: string;
    content: string;
}

interface Props {
    messages: Message[];
}

const PromptCard: React.FC<Props> = ({ messages }) => {
    const [isCopied, setCopied] = useClipboard('', { successDuration: 1000 });

    const copyRaw = () => {
        const rawText = messages
            .map((message) => `${message.role}:\n${message.content}`)
            .join('\n');
        setCopied(rawText);
    };

    const copyJson = () => {
        const jsonText = JSON.stringify(messages);
        setCopied(jsonText);
    };

    return (
        <Space direction="horizontal">
            <Space className="scroll-short" direction="vertical">
                {messages.map((item, index) => (
                    <div key={index}>
                        <span style={{ color: 'blue' }}>{item.role} </span>
                        <span>: </span>
                        <span style={{ whiteSpace: 'pre-line' }}>{item.content}</span>
                    </div>
                ))}
            </Space>
            <Space direction="vertical">
                <Button className="right" onClick={copyJson}>
                    Copy to JSON
                </Button>
                <Button className="right" onClick={copyRaw}>
                    Copy to RAW
                </Button>
            </Space>
        </Space>
    );
};

export default PromptCard;

// web/src/components/PromptCard.vue
<script setup lang="ts">
import {useClipboard} from '@vueuse/core';
import {useRouter} from 'vue-router';
import type {Message} from "@/sdk/models";


const {text, copy, copied, isSupported} = useClipboard({})

const router = useRouter()

const props = defineProps<{
    messages: Message[]
}>()


function copyRaw() {
    let res: string[] = []
    props.messages.forEach((m) => {
        res.push(m.role + ":\n" + m.content)
    })
    let whole = res.join('\n')
    copy(whole)

}

function copyJson() {
    let payload = JSON.stringify(props.messages)
    copy(payload)
}


</script>

<template>
    <a-space direction="horizontal">
        <a-space class="scroll-short" direction="vertical">
            <div v-for="item in messages">
                <span :style="{ color: 'blue' }">{{ item.role }} </span><span>:&nbsp;</span>
                <span style="white-space: pre-line"> {{ item.content }}</span>
            </div>
        </a-space>
        <a-space direction="vertical">
            <a-button @click="copyJson" class="right">Copy to JSON</a-button>
            <a-button @click="copyRaw" class="right">Copy to RAW</a-button>
        </a-space>
    </a-space>
</template>

<style scoped>
.scroll-short {
    height: 200px;
    /* 设置组件容器的固定高度 */
    overflow: auto;
    /* 设置溢出部分自动滚动 */
}

.floating-container {
    position: fixed;

}

.right {
    float: right;
    text-align: right;
    /* additional styles if needed */
}
</style>
