// web2/src/components/PromptInput.tsx
import React, { useState } from 'react';
import {
    CloseOutlined,
    DownOutlined,
    PlusOutlined,
    UpOutlined,
} from '@ant-design/icons';
import { Button, Divider, Popconfirm, Radio, Switch, Space, Typography, Row, Col, Input } from 'antd';

interface Message {
    role: string;
    content: string;
    enable: boolean;
}

interface Props {
    messages: Message[];
    withControl?: boolean;
    withCopy?: boolean;
    withSidebar?: boolean;
    title?: string;
    withEnable?: boolean;
    onOrderUp: (index: number) => void;
    onOrderDown: (index: number) => void;
    onRemove: (index: number) => void;
    onAdd: (index: number) => void;
}

const PromptInput: React.FC<Props> = ({
    messages,
    withControl = false,
    withCopy = false,
    withSidebar = false,
    title = '',
    withEnable = false,
    onOrderUp,
    onOrderDown,
    onRemove,
    onAdd,
}) => {
    const [selectedRole, setSelectedRole] = useState<string>('');

    const color = (role: string) => {
        switch (role) {
            case 'user':
                return { color: 'blue' };
            case 'system':
                return { color: 'red' };
            case 'assistant':
                return { color: 'black' };
            default:
                return {};
        }
    };

    const handleCopy = (content: string) => {
        navigator.clipboard.writeText(content).then(() => {
            alert('Content copied to clipboard');
        });
    };

    const dragData = () => {
        return messages.map((_, index) => index);
    };

    return (
        <div>
            {messages.map((item, index) => (
                <div key={index}>
                    {(withEnable && item.enable) || !withEnable ? (
                        <Row>
                            {withControl && (
                                <Divider>
                                    <Space>
                                        <Button onClick={() => onAdd(index)}>
                                            <PlusOutlined />
                                        </Button>
                                        <Divider type="vertical" />
                                        <Button
                                            type="primary"
                                            shape="round"
                                            onClick={() => onOrderUp(index)}
                                        >
                                            <UpOutlined />
                                        </Button>
                                        <Button
                                            type="primary"
                                            shape="round"
                                            onClick={() => onOrderDown(index)}
                                        >
                                            <DownOutlined />
                                        </Button>
                                        <Divider type="vertical" />
                                        <Popconfirm
                                            title="Are you sure delete this task?"
                                            onConfirm={() => onRemove(index)}
                                            okText="Yes"
                                            cancelText="No"
                                        >
                                            <Button>
                                                <CloseOutlined />
                                            </Button>
                                        </Popconfirm>
                                    </Space>
                                </Divider>
                            )}
                            <Row>
                                <Space direction="vertical">
                                    {!withSidebar && (
                                        <Radio.Group
                                            value={item.role}
                                            onChange={(e) => setSelectedRole(e.target.value)}
                                            buttonStyle="solid"
                                        >
                                            <Radio.Button value="user">User</Radio.Button>
                                            <Radio.Button value="system">System</Radio.Button>
                                            <Radio.Button value="assistant">Assistant</Radio.Button>
                                        </Radio.Group>
                                    )}
                                </Space>
                                <Divider type="vertical" />
                                <Space direction="horizontal">
                                    {withSidebar && (
                                        <Button style={color(item.role)}>
                                            {item.role}
                                        </Button>
                                    )}
                                    {withControl && (
                                        <>
                                            <Typography.Text>Enable</Typography.Text>
                                            <Switch
                                                checked={item.enable}
                                                onChange={(checked) => {
                                                    item.enable = checked;
                                                }}
                                            />
                                        </>
                                    )}
                                    {withCopy && (
                                        <Button onClick={() => handleCopy(JSON.stringify(item.content))}>
                                            Copy JSON
                                        </Button>
                                    )}
                                </Space>
                            </Row>
                            <Row gutter={12} align="middle">
                                <Col span={24}>
                                    <Input.TextArea
                                        disabled={!item.enable}
                                        value={item.content}
                                        onChange={(e) => {
                                            item.content = e.target.value;
                                        }}
                                        autoSize={{ minRows: 3, maxRows: 5 }}
                                        placeholder="textarea with clear icon"
                                    />
                                </Col>
                            </Row>
                        </Row>
                    ) : null}
                </div>
            ))}
        </div>
    );
};

export default PromptInput;

// web/src/components/PromptInput.vue
<script setup lang="ts">

import { CloseOutlined, DownOutlined, PlusOutlined, UpOutlined } from "@ant-design/icons-vue";

import { useClipboard } from '@vueuse/core';
import { useRouter } from 'vue-router';

import type { Message } from "../../sdk";


const { text, copy, copied, isSupported } = useClipboard({})

const router = useRouter()

const emit = defineEmits<{
    (e: 'orderUp', index: number): void
    (e: 'orderDown', index: number): void
    (e: 'remove', index: number): void
    (e: 'add', index: number): void
}>()



export interface Props {
    messages: Message[],
    withControl?: boolean,
    withCopy?: boolean
    withSidebar?: boolean
    title?: string
    withEnable?: boolean
}

const props = withDefaults(defineProps<Props>(), {
    withControl: false,
    withCopy: false,
    withSidebar: false,
    title: "",
    withEnable: false,
}
)


function orderUp(index,) {
    emit('orderUp', index,)
}

function orderDown(index,) {
    emit('orderDown', index,)
}

function add(index) {
    emit('add', index)
}

function remove(index) {
    emit('remove', index)
}

function color(role: string) {
    switch (role) {
        case 'user':
            return { color: 'blue' }

            break;
        case 'system':
            return { color: 'red' }

        case 'assitant':
            return { color: 'black' }
            break
        default:
            break;
    }
}

const dragData = () => {
    let res = []
    for (let i = 0; i < props.messages.length; i++) {
        res.push(i)
    }
    return res
}

</script>

<template>
    <!-- <draggable v-model="props.messages" key="content">
        <template #item="{ element }">
            <div> {{ element.content }} </div>
        </template>
    </draggable> -->

    <div v-for="(item, index) in messages" :key="index">
        <div v-if="(withEnable && item.enable) || (!withEnable)">
            <a-row v-if="withControl">
                <a-divider>
                    <a-space>
                        <a-button @click="add(index)">
                            <template #icon>
                                <PlusOutlined />
                            </template>
                        </a-button>

                        <a-divider type="vertical"></a-divider>

                        <!-- up down the order -->
                        <a-button type="primary" shape="round" @click="orderUp(index,)">
                            <template #icon>
                                <UpOutlined />
                            </template>
                        </a-button>
                        <a-button type="primary" shape="round" @click="orderDown(index)">
                            <template #icon>
                                <DownOutlined />
                            </template>
                        </a-button>

                        <a-divider type="vertical"></a-divider>

                        <a-popconfirm title="Are you sure delete this task?" ok-text="Yes" cancel-text="No"
                            @confirm="remove(index)">
                            <a-button>
                                <template #icon>
                                    <CloseOutlined />
                                </template>
                            </a-button>
                        </a-popconfirm>

                    </a-space>

                </a-divider>
            </a-row>
            <a-row>
                <!-- role -->
                <a-space direction="vertical">
                    <a-radio-group v-if="!withSidebar" v-model:value="item.role" option-type="button" button-style="solid">
                        <a-radio-button value="user">User</a-radio-button>
                        <a-radio-button value="system">System</a-radio-button>
                        <a-radio-button value="assistant">Assitant</a-radio-button>
                    </a-radio-group>
                </a-space>
                <a-divider type="vertical"></a-divider>

                <!-- enable toggle -->
                <a-space direction="horizontal">
                    <a-button v-if="withSidebar" :style="color(item.role)">
                        {{ item.role }}
                    </a-button>
                    <a-space v-if="withControl">
                        <a-typography-text>Enable</a-typography-text>
                        <a-switch v-model:checked="item.enable"></a-switch>
                    </a-space>
                    <a-button v-if="withCopy" @click="copy(JSON.stringify(item.content))">Copy JSON</a-button>
                </a-space>
            </a-row>
            <a-row :gutter="12" align="middle">

                <a-col :span='24'>
                    <!-- content edit -->
                    <a-textarea :disabled="!item.enable" v-model:value="item.content"
                        :auto-size="{ minRows: 3, maxRows: 5 }" placeholder="textarea with clear icon" />
                </a-col>

            </a-row>
        </div>
    </div>
</template>

<style scoped></style>
